### ISSUE TITLE
Oracle DefaultFullTextSearchStmt fails

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [cismet/cids-server#176]
Oracle DefaultFullTextSearchStmt fails with:

``SDO_GEOMETRY  Comparison of nested table or VARRAY or LOB attributes of an object type was attempted in the absence of a MAP or ORDER method.``

Reason: SDO_GEOMETRY not comparable, DISTINCT not allowed
Solution: https://community.oracle.com/message/2529805#2529805

**Comment by p-a-s-c-a-l** [comment]
```java 
java.lang.ExceptionInInitializerError
	at Sirius.server.middleware.types.MetaObjectNode.<init>(MetaObjectNode.java:145)
	at de.cismet.cids.server.search.builtin.DefaultFullTextSearch.performServerSearch(DefaultFullTextSearch.java:186)
	at Sirius.server.middleware.impls.proxy.SearchServiceImpl.customServerSearch(SearchServiceImpl.java:72)
	at Sirius.server.middleware.impls.proxy.ProxyImpl.customServerSearch(ProxyImpl.java:828)
	at de.cismet.cids.server.ws.rest.RESTfulSerialInterface.customServerSearchPOST(RESTfulSerialInterface.java:1714)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:320)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:842)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:648)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:450)
Caused by: org.openide.util.lookup.ALPairComparator$DuplicatedPairException: Duplicate pair in treePair1: de.cismet.cids.server.actions.BandwidthTestAction pair2: java.lang.Object index1: 9 index2: 9 item1: de.cismet.cids.server.actions.BandwidthTestAction@1cad203c item2: null id1: 74d998e6 id2: 676088e3

	at org.openide.util.lookup.ALPairComparator.compare(ALPairComparator.java:69)
	at org.openide.util.lookup.ALPairComparator.compare(ALPairComparator.java:54)
	at java.util.TreeMap.put(TreeMap.java:552)
	at java.util.TreeSet.add(TreeSet.java:255)
	at org.openide.util.lookup.AbstractLookup.getPairsAsLHS(AbstractLookup.java:322)
	at org.openide.util.lookup.MetaInfServicesLookup.beforeLookup(MetaInfServicesLookup.java:153)
	at org.openide.util.lookup.AbstractLookup$R.beforeLookup(AbstractLookup.java:1126)
	at org.openide.util.lookup.ProxyLookup$R.myBeforeLookup(ProxyLookup.java:676)
	at org.openide.util.lookup.ProxyLookup$R.computeResult(ProxyLookup.java:526)
	at org.openide.util.lookup.ProxyLookup$R.allInstances(ProxyLookup.java:497)
	at org.openide.util.Lookup.lookupAll(Lookup.java:263)
	at de.cismet.cids.utils.ClassloadingHelper.<clinit>(ClassloadingHelper.java:113)
```

**Comment by p-a-s-c-a-l** [comment]
done
